AWSTemplateFormatVersion: 2010-09-09
Resources: 
# VPCの作成
  Task10VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: VPCfromCF
# サブネット（パブリック）の作成
  SubnetPb1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !Ref Task10VPC
      CidrBlock: 192.168.3.0/24
      Tags:
        - Key: Name
          Value: SubnetPb1fromCF
  SubnetPb2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      VpcId: !Ref Task10VPC
      CidrBlock: 192.168.4.0/24
      Tags:
        - Key: Name
          Value: SubnetPb2fromCF
# サブネット（プライベート）の作成
  SubnetPv1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !Ref Task10VPC
      CidrBlock: 192.168.1.0/24
      Tags:
        - Key: Name
          Value: SubnetPv1fromCF
  SubnetPv2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      VpcId: !Ref Task10VPC
      CidrBlock: 192.168.2.0/24
      Tags:
        - Key: Name
          Value: SubnetPv2fromCF
# インターネットゲートウェイの作成
  Task10igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGWfromCF
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Task10VPC
      InternetGatewayId: !Ref Task10igw
# ルートテーブルの作成
  Task10routeTable01:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Task10VPC
      Tags:
        - Key: Name
          Value: RouteTable-Pb01fromCF
  Task10routeTable02:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Task10VPC
      Tags:
        - Key: Name
          Value: RouteTable-Pb02fromCF
# インターネットゲートウェイへルートテーブルをアタッチ
  Route01:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref Task10routeTable01
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Task10igw
  Route02:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref Task10routeTable02
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Task10igw
# ルートテーブルへサブネットを関連付け
  routeTableAssoc01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPb1
      RouteTableId: !Ref Task10routeTable01
  routeTableAssoc02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPb2
      RouteTableId: !Ref Task10routeTable02

Outputs:
  VPC:
    Description: Information about the value
    Value: !Ref Task10VPC
    Export: 
      Name: VPCName

  SubnetPb1:
    Description: Information about the value
    Value: !Ref SubnetPb1
    Export: 
      Name: SubnetPb1Name

  SubnetPb2:
    Description: Information about the value
    Value: !Ref SubnetPb2
    Export: 
      Name: SubnetPb2Name
  
  SubnetPv1:
    Description: Information about the value
    Value: !Ref SubnetPv1
    Export: 
      Name: SubnetPv1Name

  SubnetPv2:
    Description: Information about the value
    Value: !Ref SubnetPv2
    Export: 
      Name: SubnetPv2Name