AWSTemplateFormatVersion: 2010-09-09
Description: CF-Security
Parameters:
  MyIP:
    Description: MyIPadress
    Type: String
    Default: 14.10.82.193/32
  IP:
    Description: 0.0.0.0/0
    Type: String
    Default: 0.0.0.0/0
# EC2のセキュリティグループを作成
Resources: 
  EC2secGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2-SG
      GroupDescription: EC2-SG
      VpcId:  !ImportValue VPCName
      SecurityGroupIngress:
        - IpProtocol: tcp
          Fromport: 22
          Toport: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          Fromport: 80
          Toport: 80
          CidrIp: !Ref IP
      Tags:
        - Key: Name
          Value: EC2SGfromCF

# RDSのセキュリティグループを作成
  RDSsecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: RDS_sg
      GroupDescription: RDS
      VpcId: !ImportValue VPCName
      SecurityGroupIngress:
        IpProtocol: tcp
        Fromport: 3306
        Toport: 3306
        SourceSecurityGroupID: !Ref EC2secGroup
      Tags:
        - Key: Name
          Value: RDSSGfromCF

# ELBのセキュリティグループを作成
  ALBsecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: alb_sg 
      GroupDescription: alb 
      VpcId: !ImportValue VPCName
      SecurityGroupIngress:
        - IpProtocol: tcp
          Fromport: 80
          Toport: 80
          CidrIp: !Ref IP
      Tags:
        - Key: Name
          Value: ALBfromCF
          
Outputs:
  EC2SG:
    Description: Information about the value
    Value: !Ref EC2secGroup
    Export: 
      Name: EC2SGName
  DBSG:
    Description: Information about the value
    Value:  !Ref RDSsecGroup
    Export: 
      Name: RDSSGName
  ELBSG:
    Description: Information about the value
    Value:  !Ref ALBsecGroup
    Export: 
      Name: ELBSGName